# Generated by Django 5.1.2 on 2025-04-12 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, choices=[('obuvnoy-rojok', 'Обувной рожок'), ('obuvnoy-mech', 'Обувной меч'), ('nabor', 'Наборы'), ('podves', 'Подвес'), ('kobura', 'Кобура'), ('nojny', 'Ножны'), ('gardy', 'Гарды'), ('upakovka', 'Упаковка'), ('other', 'Другое')], max_length=70, verbose_name='Категория товара')),
                ('name', models.CharField(blank=True, max_length=270, verbose_name='Название товара')),
                ('remains', models.CharField(blank=True, max_length=270, verbose_name='Остаток на складе')),
                ('thickness', models.FloatField(blank=True, null=True, verbose_name='Толщина товара')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Длина товара')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('set', models.CharField(blank=True, max_length=270, verbose_name='Комплект товара')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('cover', models.ImageField(blank=True, upload_to='images/post')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/articles/')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.articles')),
            ],
        ),
    ]
