version: '3.8'
services:
  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"  # Возвращаем порт 8000
    volumes:
      - static_volume:/app/static  # Для STATIC_ROOT
      - media_volume:/app/media    # Для MEDIA_ROOT (вместо /app/products/media)
    environment:
      - DJANGO_DEBUG=True

volumes:
    static_volume:
    media_volume: