version: '3.8'
services:
  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"  # Возвращаем порт 8000
    volumes:
      - .:/app
      - ./static:/app/static  # Явное монтирование статики
    environment:
      - DJANGO_DEBUG=True